name: montra
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  build_runner: ^2.4.12
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  dropdown_search: ^5.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.2.0
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  mockito: ^5.4.4
  otp_pin_field: ^1.2.9+1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
